name: Analyze Areopa (weekly)

on:
  schedule:
    # Every Wednesday at 03:00 UTC
    - cron: '0 3 * * 3'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Run analyze (Areopa)
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_DEPLOYMENT }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
        run: |
          python -m src.yt_tool.cli analyze \
            --channel-id UCWL0RbbT6ILzzCd6Ix7t0AQ \
            --data-dir data \
            --taxonomy data/taxonomy.json \
            --restrict-to-taxonomy \
            --export-markmap \
            --root-title "Areopa Webinars" \
            --root-url "https://areopa.academy/"
      - name: Create/Update latest release and upload assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: latest
          name: Latest analysis
          make_latest: true
          files: |
            data/videos.json
            data/speaker_stats.json
            data/videos_markmap.md

